# For full config options, check the docs:
#    docs.serverless.com


service: serverless-w-import

frameworkVersion: '2'

provider:
  name: aws
  runtime: python3.8
  lambdaHashingVersion: 20201221


functions:
  hello:
    handler: handler.hello

	
plugins:
  - serverless-python-requirements
custom:
  pythonRequirements:
    dockerizePip: true
